import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "path";
import runtimeErrorOverlay from "@replit/vite-plugin-runtime-error-modal";
import { VitePWA } from "vite-plugin-pwa";

const rawPort = process.env.PORT;

if (!rawPort) {
  throw new Error(
    "PORT environment variable is required but was not provided.",
  );
}

const port = Number(rawPort);

if (Number.isNaN(port) || port <= 0) {
  throw new Error(`Invalid PORT value: "${rawPort}"`);
}

const basePath = process.env.BASE_PATH;

if (!basePath) {
  throw new Error(
    "BASE_PATH environment variable is required but was not provided.",
  );
}

const pwaEnabled = process.env.PWA_ENABLED !== "false";

export default defineConfig({
  base: basePath,
  plugins: [
    react(),
    tailwindcss(),
    runtimeErrorOverlay(),
    ...(pwaEnabled
      ? [
          VitePWA({
            registerType: "prompt",
            // Service worker generated by Workbox at build time
            strategies: "generateSW",
            // In dev mode expose the SW so Chrome DevTools Application tab works
            devOptions: {
              enabled: true,
              type: "module",
            },
            includeAssets: [
              "favicon.svg",
              "icons/icon-192.png",
              "icons/icon-512.png",
              "icons/icon-maskable-512.png",
            ],
            manifest: {
              name: "HyperFlow Operator",
              short_name: "HyperFlow",
              description: "HyperFlow AI agent operator panel",
              theme_color: "#0f172a",
              background_color: "#0f172a",
              display: "standalone",
              orientation: "portrait-primary",
              scope: basePath,
              start_url: basePath,
              icons: [
                {
                  src: "icons/icon-192.png",
                  sizes: "192x192",
                  type: "image/png",
                },
                {
                  src: "icons/icon-512.png",
                  sizes: "512x512",
                  type: "image/png",
                },
                {
                  src: "icons/icon-maskable-512.png",
                  sizes: "512x512",
                  type: "image/png",
                  purpose: "maskable",
                },
              ],
              shortcuts: [
                {
                  name: "Active Runs",
                  short_name: "Runs",
                  description: "View currently active agent runs",
                  url: `${basePath}runs`,
                  icons: [{ src: "icons/icon-192.png", sizes: "192x192" }],
                },
                {
                  name: "Agents",
                  short_name: "Agents",
                  description: "Manage agents",
                  url: `${basePath}agents`,
                  icons: [{ src: "icons/icon-192.png", sizes: "192x192" }],
                },
              ],
            },
            workbox: {
              // Cache app shell assets with cache-first strategy
              globPatterns: ["**/*.{js,css,html,ico,png,svg,woff2}"],
              // Runtime caching rules
              runtimeCaching: [
                {
                  // API list endpoints: stale-while-revalidate
                  // User sees cached data instantly; fresh data loads in background
                  urlPattern: /^\/api\/(agents|agent-runs)(\?.*)?$/,
                  handler: "StaleWhileRevalidate",
                  options: {
                    cacheName: "api-list-cache",
                    expiration: {
                      maxEntries: 50,
                      maxAgeSeconds: 60 * 5, // 5 minutes
                    },
                    cacheableResponse: {
                      statuses: [0, 200],
                    },
                  },
                },
                {
                  // Individual run/agent detail: network-first (always fresh)
                  urlPattern: /^\/api\/(agents|agent-runs)\/[^/]+$/,
                  handler: "NetworkFirst",
                  options: {
                    cacheName: "api-detail-cache",
                    networkTimeoutSeconds: 5,
                    expiration: {
                      maxEntries: 100,
                      maxAgeSeconds: 60 * 2, // 2 minutes
                    },
                    cacheableResponse: {
                      statuses: [0, 200],
                    },
                  },
                },
                {
                  // Metrics + health endpoints: network-first, short TTL
                  urlPattern: /^\/api\/(metrics|healthz|readyz|livez)/,
                  handler: "NetworkFirst",
                  options: {
                    cacheName: "api-health-cache",
                    networkTimeoutSeconds: 3,
                    expiration: {
                      maxEntries: 10,
                      maxAgeSeconds: 30,
                    },
                    cacheableResponse: {
                      statuses: [0, 200],
                    },
                  },
                },
              ],
              // Do not cache mutation endpoints (POST/PATCH/DELETE)
              navigateFallback: "index.html",
              navigateFallbackDenylist: [/^\/api/],
              skipWaiting: false, // We use "prompt" register type — user controls update
              clientsClaim: true,
            },
          }),
        ]
      : []),
    ...(process.env.NODE_ENV !== "production" &&
    process.env.REPL_ID !== undefined
      ? [
          await import("@replit/vite-plugin-cartographer").then((m) =>
            m.cartographer({
              root: path.resolve(import.meta.dirname, ".."),
            }),
          ),
          await import("@replit/vite-plugin-dev-banner").then((m) =>
            m.devBanner(),
          ),
        ]
      : []),
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "src"),
      "@assets": path.resolve(import.meta.dirname, "..", "..", "attached_assets"),
    },
    dedupe: ["react", "react-dom"],
  },
  root: path.resolve(import.meta.dirname),
  build: {
    outDir: path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
  },
  server: {
    port,
    host: "0.0.0.0",
    allowedHosts: true,
    fs: {
      strict: true,
      deny: ["**/.*"],
    },
    proxy: {
      "/api": {
        target: "http://localhost:8080",
        changeOrigin: true,
      },
    },
  },
  preview: {
    port,
    host: "0.0.0.0",
    allowedHosts: true,
  },
});